### Let's Scrape the data using Selenium and BeautifulSoup

In [1]:
from selenium import webdriver
from bs4 import BeautifulSoup
import time
import pandas as pd
import geocoder

In [2]:
def scraper(url: str, driver_path: str):
    """
    Method to scrape a webpage
    """
    driver = webdriver.Chrome(executable_path=driver_path)
    driver.get(url)
    time.sleep(2)
    table_element = driver.find_element_by_xpath('/html/body/div[3]/div[3]/div[4]/div/table[1]')
    data = {col.text: [] for col in table_element.find_elements_by_xpath(".//*[self::th]")}
    header = list(data.keys())
    for table_row in table_element.find_elements_by_xpath(".//*[self::tr]"):
        row_data = [table_data.text for table_data in table_row.find_elements_by_xpath(".//*[self::td]")]
        # We skip empty rows
        if not row_data:
            continue
        # We skip rows which Borough is Not assigned
        if row_data[1] == 'Not assigned':
            continue
        for i, col in enumerate(row_data):
            data[header[i]].append(col)
    frame = pd.DataFrame(data=data)
    driver.quit()
    return frame

In [3]:
URL = 'https://en.wikipedia.org/wiki/List_of_postal_codes_of_Canada:_M'
DRIVER_PATH = '/Users/koutouodilon/Documents/ibm-data-science-professional-certificate/applied-data-science-capstone/Coursera_Capstone/chromedriver'
dataframe = scraper(url=URL, driver_path=DRIVER_PATH)

In [4]:
dataframe.head()

  Postal code           Borough                                  Neighborhood
0         M3A        North York                                     Parkwoods
1         M4A        North York                              Victoria Village
2         M5A  Downtown Toronto                    Regent Park / Harbourfront
3         M6A        North York             Lawrence Manor / Lawrence Heights
4         M7A  Downtown Toronto  Queen's Park / Ontario Provincial Government

In [5]:
def transform_neighborhood(row):
    """
    Method to transform the dataframe
    """
    # If a cell has a neighbohood Not assigned, then it's the same as the Borough
    if row['Neighborhood'] == 'Not assigned':
        row['Neighborhood'] = row['Borough']

    # We split the Neighborhood and join them by comma
    neighborhoods = row['Neighborhood'].split('/')
    row['Neighborhood'] = ", ".join([n.strip() for n in neighborhoods])
    return row

In [6]:
dataframe = dataframe.apply(transform_neighborhood, axis=1)

In [7]:
dataframe.head(12)

,Postal code,Borough,Neighborhood
0,M3A,North York,Parkwoods
1,M4A,North York,Victoria Village
2,M5A,Downtown Toronto,"Regent Park, Harbourfront"
3,M6A,North York,"Lawrence Manor, Lawrence Heights"
4,M7A,Downtown Toronto,"Queen's Park, Ontario Provincial Government"
5,M9A,Etobicoke,Islington Avenue
6,M1B,Scarborough,"Malvern, Rouge"
7,M3B,North York,Don Mills
8,M4B,East York,"Parkview Hill, Woodbine Gardens"
9,M5B,Downtown Toronto,"Garden District, Ryerson"
10,M6B,North York,Glencairn
11,M9B,Etobicoke,"West Deane Park, Princess Gardens, Martin Grov..."

In [8]:
print(f"Number of rows in the dataframe: {dataframe.shape[0]}")

Number of rows in the dataframe: 103

In [18]:
geospacial_df = pd.read_csv('Geospatial_Coordinates.csv')
geospacial_df.head()

  Postal Code   Latitude  Longitude
0         M1B  43.806686 -79.194353
1         M1C  43.784535 -79.160497
2         M1E  43.763573 -79.188711
3         M1G  43.770992 -79.216917
4         M1H  43.773136 -79.239476

In [35]:
def get_location(row):
    """
    Method to add the location to the dataframe
    """
    lat_lng = geospacial_df[geospacial_df['Postal Code'] == row['Postal code']]
    row['Latitude'] = lat_lng['Latitude'].values[0]
    row['Longitude'] = lat_lng['Longitude'].values[0]
    return row

In [36]:
dataframe = dataframe.apply(get_location, axis=1)

In [37]:
dataframe.head()

,Postal code,Borough,Neighborhood,Latitude,Longitude
0,M3A,North York,Parkwoods,43.753259,-79.329656
1,M4A,North York,Victoria Village,43.725882,-79.315572
2,M5A,Downtown Toronto,"Regent Park, Harbourfront",43.654260,-79.360636
3,M6A,North York,"Lawrence Manor, Lawrence Heights",43.718518,-79.464763
4,M7A,Downtown Toronto,"Queen's Park, Ontario Provincial Government",43.662301,-79.389494